framework:
    cache:
        pools:
            cache.pos_ratios:
                adapter: cache.adapter.redis
                provider: '%env(resolve:CACHE_DSN)%'

        app: cache.adapter.redis
        default_redis_provider: '%env(resolve:CACHE_DSN)%'